import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Matching BO",
  description: "Generated by Matching BO",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
